# Generated by Django 5.1.2 on 2024-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_user_active_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
