# Generated by Django 5.1.2 on 2024-10-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTag',
            new_name='LessonTags',
        ),
    ]
